"""
Assembles web/data.js for the Bun Bang Fai (บั๊งบึงไฟ) provincial regulation
GIS website from the individual data files so the page works from a plain
file:// path with zero fetch() calls.
"""
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(os.path.dirname(BASE), "research")
OUT = os.path.join(BASE, "web", "data.js")


def load(name, use_web_data=False):
    path = (
        os.path.join(BASE, "web", "data", name) if use_web_data
        else os.path.join(RES, name)
    )
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def main():
    provinces = load("provinces_clean.geojson")
    prov_ref = load("provinces_ref.json")
    prov_data = load("prov_data.json")
    airports = load("airports_enhanced.json", use_web_data=True)

    def j(obj):
        return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))

    parts = [
        "// AUTO-GENERATED by data_prep/build_data_js.py — do not edit by hand.",
        "// Bun Bang Fai (บั๊งบึงไฟ) provincial regulations + airport safe navigation",
        "// zones — Thailand, 77 provinces + Bangkok. Inlined as JS (not fetch()) so",
        "// the page works when opened directly as a local file:// (no server needed).",
        "",
        "// PROVINCES: GADM level-1 boundaries (77 provinces incl. Bueng Kan merged",
        "// from geoBoundaries; 2 lake artifacts removed). NAME_1 keyed.",
        f"var PROVINCES = {j(provinces)};",
        "",
        "// PROV_REF: per-province display metadata (Thai name, region, centroid).",
        f"var PROV_REF = {j(prov_ref)};",
        "",
        "// PROV_DATA: per-province regulation summary (proclamation title, permit",
        "// authority, advance-notice days, airport notification, festival notes,",
        "// penalties, source URL). Keyed by GADM NAME_1; Bangkok uses",
        "// 'Bangkok Metropolis'.",
        f"var PROV_DATA = {j(prov_data)};",
        "",
        "// AIRPORTS: public ARP coordinates + longest-runway bearing from the base",
        "// birdheatmap repo (sourced from OurAirports; BTZ verified vs AIP AD 2.12).",
        "// Extended with safe-zone info for the regulation map.",
        f"var AIRPORTS = {j(airports)};",
        "",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print("Wrote", OUT, f"({sum(len(p) for p in parts)} chars)")


if __name__ == "__main__":
    main()
